site_name: PIGLET
nav:
     - PIGLET: index.md
     - Use Cases: use-cases.md
     - Glossary: glossary.md
     - Ethical Considerations: ethical-considerations.md
     - About: about.md
theme: readthedocs
